#version: '3.8'
services:
  # postgres:
  #   image: postgres
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_PASSWORD='securepswd'
     
  django:
    build: 
     context: .  
    volumes:     
      - .:/usr/src/app  
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - postgres

# volumes:
#   pgdata:
   