services:
  postgres:
    image: postgres:15
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mahdi -d pyrodb"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - backend.env
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres-data:
