# Generated by Django 4.2.16 on 2024-11-02 16:13

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
